### ISSUE TITLE
iOS 13 Socket Connection Implementation

### ISSUE THREAD

**Issue by mjjimenez** [OpenMined/SwiftSyft#15]
As referenced in #3 , this is the socket connection implementation that will be used by the signalling client. It should conform to the `SocketClientProtocol` and be responsible for maintaining socket connection via ping, sending and receiving data.

For iOS 13, use `URLSessionWebSocketTask`.

**Comment by mamuleanu** [comment]
@mjjimenez  Please assign this issue to me.
