### ISSUE TITLE
iOS 12 Socket Connection Implementation

### ISSUE THREAD

**Issue by mjjimenez** [OpenMined/SwiftSyft#16]
As referenced in #3 , this is the socket connection implementation that will be used by the signalling client. It should conform to the `SocketClientProtocol` and be responsible for maintaining socket connection via ping, sending and receiving data.

For iOS 12, you can research for a updated socket connection library that supports all of our requirements specified in #3 . Please post it here so we can discuss the pros and cons of your chosen library. 

For reference, in the WebRTC iOS demo here: https://github.com/stasel/WebRTC-iOS , uses https://github.com/daltoniam/Starscream

**Comment by SashaBataieva** [comment]
@mjjimenez please, assign it to me

**Comment by mjjimenez** [comment]
#20 closes this.
