### ISSUE TITLE
Set up deployment to Cocoapods

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#27]
We need to at some point deploy SwiftSyft onto Cocoapods so that it may be used in libraries.

Here's the corresponding Android issue: https://github.com/OpenMined/KotlinSyft/issues/3

**Comment by mjjimenez** [comment]
- [ ] Github action to release to cocoapods
- [ ] Generate API documentation on release in github actions using sourcedocs (https://github.com/eneko/SourceDocs) using `sourcedocs generate -t --module-name=SwiftSyft -- -scheme SwiftSyft-Example -workspace SwiftSyft.xcworkspace`
