### ISSUE TITLE
Implement Protobuf classes in iOS

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#31]
We need to add the following Protobuf classes to SwiftSyft as they are completed:

- [x] `Plan`
- [x] `State`
- [x] `Operation`
- [x] `Placeholder`
- [x] `TorchParameter`
- [x] `Protocol`
- [x] `PromiseTensor`
- [x] ... more to be defined

**Comment by mjjimenez** [comment]
Swift Syft-Proto stubs have been merged here https://github.com/OpenMined/syft-proto/commit/f50de2e381704a7ae20dfdd1d0d4b5f648a22e0c but has not been published to cocoapods yet. Will create a new issue to create cocoapods podspec in Syft-Proto.
