### ISSUE TITLE
Implement sleep/wake detection in iOS

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#37]
While we want to allow the end-user developer integrating SwiftSyft into their application the ability to choose to execute models while the user is asleep, we don't want to force them into this paradigm.

This issue includes developing a basic "asleep or awake" algorithm that a developer can choose to use. It's worth noting that the default option for a syft client would be to "enable" this as a requirement for training. It's up to the developer to state that they want this option "disabled".

**Comment by mjjimenez** [comment]
This will be closed since background scheduling is now the responsibility of the library user.

**Comment by cereallarceny** [comment]
So long as you provide an example of this in your examples.
