### ISSUE TITLE
Add support for charge detection and wifi detection in iOS

### ISSUE THREAD

**Issue by cereallarceny** [OpenMined/SwiftSyft#38]
While we want to allow the end-user developer integrating SwiftSyft into their application the ability to choose to execute models while the user is charging their phone, we don't want to force them into this paradigm.

This issue includes developing charge detection that a developer can choose to use. It's worth noting that the default option for a syft client would be to "enable" this as a requirement for training. It's up to the developer to state that they want this option "disabled".

**Comment by mjjimenez** [comment]
Closed in #101
