### ISSUE TITLE
Implement FL Authentication and Cycle API Request

### ISSUE THREAD

**Issue by mjjimenez** [OpenMined/SwiftSyft#47]
This will be implemented in `SyftClient` class `start` method here : https://github.com/OpenMined/SwiftSyft/blob/master/SwiftSyft/Classes/SyftClient.swift#L28

The API requests are described here:
https://github.com/OpenMined/PyGrid/issues/445
Refer to **Authentication with PyGrid** and **FL Worker Cycle Request**

The requests can be made by socket messages or HTTP requests but this issue is mainly for the HTTP requests made using `URLSession.dataTaskPublisher` and chaining the requests.

A seperate issue will be made for using signalling requests.

**Comment by SashaBataieva** [comment]
@mjjimenez Please, assign it for me

**Comment by mjjimenez** [comment]
@SashaBataieva for the PyGrid API here, they're not live yet but we can proceed with creating the requests on the iOS side for now.

You can follow the updates on that issue here https://github.com/OpenMined/PyGrid/issues/445

If you have any questions regarding `Combine` framework, and URLSessionDataTask publisher, we can discuss it here or in slack. I'm just starting to familiarize myself in using it too.

**Comment by mjjimenez** [comment]
Closed by #60
