### ISSUE TITLE
Can't build app for a real device, have error "does not contain bitcode"

### ISSUE THREAD

**Issue by SashaBataieva** [OpenMined/SwiftSyft#8]
SwiftSyft/Example/Pods/LibTorch/install/lib/libtorch.a(CPUGenerator.cpp.o)’ does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. file ‘/Pods/LibTorch/install/lib/libtorch.a’ for architecture arm64

**Comment by mjjimenez** [comment]
@SashaBataieva , I've disabled bitcode on both SwiftSyft and the example app here: #12 . I've tested it on my iPhone and there were no problems. Can you test the branch on your device just to make sure it's not a device specific problem?

**Comment by SashaBataieva** [comment]
@mjjimenez I will test it in a few hours and back to you with a result

**Comment by SashaBataieva** [comment]
@mjjimenez everything works fine :)

**Comment by mjjimenez** [comment]
Fixed by #12 . Thanks @SashaBataieva !
